/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Toolkit;

/**
 *
 * @author abrah
 */
public class Login extends javax.swing.JFrame {
    
    //Definir credenciales
        String USER1 = "azmorales";
        String PASS1 = "f1driver";
        String USER2 = "JeruiZ";
        String PASS2 = "f1manager";
        String USER3 = "rjimenez";
        String PASS3 = "f1inge";
        String USER4 = "hhmoreno";
        String PASS4 = "f1ingeniero";
        String USER5 = "elverdugo";
        String PASS5 = "f1conductor";
        
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("F1 Login");
        setResizable(false);
        SetImageLabel(JLdrift, "src/Iconos/carros.png");
        try {
        // Obtenemos la imagen desde la ruta de recursos del proyecto
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Iconos/f1logo.png"));
        this.setIconImage(icon);
    } catch (Exception e) {
        System.out.println("No se pudo cargar el icono: " + e.getMessage());
    }
       }

    
    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon (root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPcontenedor = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jLcontra = new javax.swing.JLabel();
        jPcontra = new javax.swing.JPasswordField();
        jBlogin = new javax.swing.JButton();
        jBOlvide = new javax.swing.JButton();
        jLconductor = new javax.swing.JLabel();
        jLbloquear = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLpropiedad = new javax.swing.JLabel();
        JLdrift = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 36, 66));

        jLtitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLtitulo.setText("F1 CONTRACTS MANAGER");

        jPcontenedor.setBackground(new java.awt.Color(66, 66, 87));
        jPcontenedor.setForeground(new java.awt.Color(66, 66, 87));

        jLUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLUsuario.setText("Usuario");

        jTUsuario.setBackground(new java.awt.Color(36, 36, 66));
        jTUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTUsuario.addActionListener(this::jTUsuarioActionPerformed);

        jLcontra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLcontra.setForeground(new java.awt.Color(255, 255, 255));
        jLcontra.setText("Contraseña");

        jPcontra.setBackground(new java.awt.Color(36, 36, 66));
        jPcontra.setForeground(new java.awt.Color(255, 255, 255));

        jBlogin.setBackground(new java.awt.Color(204, 0, 0));
        jBlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBlogin.setForeground(new java.awt.Color(255, 255, 255));
        jBlogin.setText("Acceder al sistema");
        jBlogin.setToolTipText("");
        jBlogin.addActionListener(this::jBloginActionPerformed);

        jBOlvide.setBackground(new java.awt.Color(66, 66, 87));
        jBOlvide.setForeground(new java.awt.Color(255, 255, 255));
        jBOlvide.setText("Olvidé mi contraseña");
        jBOlvide.addActionListener(this::jBOlvideActionPerformed);

        jLconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/conductor.png"))); // NOI18N
        jLconductor.setText("jLconductor");

        jLbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bloquear.png"))); // NOI18N
        jLbloquear.setText("jLabel2");

        javax.swing.GroupLayout jPcontenedorLayout = new javax.swing.GroupLayout(jPcontenedor);
        jPcontenedor.setLayout(jPcontenedorLayout);
        jPcontenedorLayout.setHorizontalGroup(
            jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcontenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBOlvide)
                .addGap(66, 66, 66))
            .addGroup(jPcontenedorLayout.createSequentialGroup()
                .addGroup(jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcontenedorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPcontenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcontenedorLayout.createSequentialGroup()
                                .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLconductor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPcontenedorLayout.createSequentialGroup()
                                .addComponent(jLcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTUsuario)
                            .addComponent(jPcontra))))
                .addContainerGap())
        );
        jPcontenedorLayout.setVerticalGroup(
            jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcontenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLconductor))
                .addGap(18, 18, 18)
                .addGroup(jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcontra)
                    .addGroup(jPcontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLbloquear)))
                .addGap(18, 18, 18)
                .addComponent(jBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBOlvide)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLpropiedad.setForeground(new java.awt.Color(204, 204, 204));
        jLpropiedad.setText("Propiedad de The Leyends Racing. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPcontenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLdrift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLpropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLtitulo)
                        .addGap(92, 92, 92))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLdrift, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPcontenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLpropiedad)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsuarioActionPerformed

    private void jBloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBloginActionPerformed
        //Obtener los datos ingresados por el usuario
        String username = jTUsuario.getText();
        // Obtener la contraseña
        String password = new String(jPcontra.getPassword());
        
        // Validar campos vacíos
        if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Valide los campos, por favor.", "Campos incompletos.",
                JOptionPane.WARNING_MESSAGE);
        return;
    }//GEN-LAST:event_jBloginActionPerformed

        if ((username.equals(USER1) && password.equals(PASS1)) || 
            (username.equals(USER2) && password.equals(PASS2)) ||
            (username.equals(USER3) && password.equals(PASS3)) ||
            (username.equals(USER4) && password.equals(PASS4)) ||
            (username.equals(USER5) && password.equals(PASS5))) {
            JOptionPane.showMessageDialog(this, "Bienvenido al Sistema.", "Login Exitoso", JOptionPane.INFORMATION_MESSAGE);
            
            //Instancia de la Pantalla Principal
            PantallaPrincipal principal = new PantallaPrincipal();
            principal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    private void jBOlvideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOlvideActionPerformed
        String userConfirm = JOptionPane.showInputDialog(this, "Ingrese su nombre de usuario:", "Recuperar contraseña", JOptionPane.QUESTION_MESSAGE);
        
        //Validar si el usuario existe 
        if (userConfirm != null && (userConfirm.equals(USER1) || userConfirm.equals(USER2) || userConfirm.equals(USER3) || userConfirm.equals(USER4) || userConfirm.equals(USER5))) {
            
        //Solicitar nueva contraseña
            String nuevaPass = JOptionPane.showInputDialog(this, 
            "Ingrese su nueva contraseña:", 
            "Cambio de credenciales", JOptionPane.PLAIN_MESSAGE);
            
        if (nuevaPass != null && !nuevaPass.trim().isEmpty()) {
                if(userConfirm.equals(USER1)) PASS1 = nuevaPass;
                if(userConfirm.equals(USER2)) PASS2 = nuevaPass;
                if(userConfirm.equals(USER3)) PASS3 = nuevaPass;
                if(userConfirm.equals(USER4)) PASS4 = nuevaPass;
                if(userConfirm.equals(USER5)) PASS5 = nuevaPass;
                
            //Actualizar contraseña
                JOptionPane.showMessageDialog(this, "Contraseña actualizada con éxito!"); 
        }
    }else if (userConfirm != null) {
        JOptionPane.showMessageDialog(this, 
            "El usuario no es válido.", 
            "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jBOlvideActionPerformed
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLdrift;
    private javax.swing.JButton jBOlvide;
    private javax.swing.JButton jBlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLbloquear;
    private javax.swing.JLabel jLconductor;
    private javax.swing.JLabel jLcontra;
    private javax.swing.JLabel jLpropiedad;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPcontenedor;
    private javax.swing.JPasswordField jPcontra;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
